# Generated by Django 2.2.9 on 2022-07-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220718_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descriprion',
            new_name='description',
        ),
    ]
